### ISSUE TITLE
Do we need to add a caveat for keeping Docker images updated?

### ISSUE THREAD

**Issue by nigeldgreen** [UoMResearchIT/docker-introduction#12]
If you create an image to use (instead of users running a Dockerfile to build up a container), should we mention that this needs to be tended over time to prevent things becoming stale or outdated?

**Comment by OliverWoolland** [comment]
In the rewrite our approach has been more 'getting started with day to day life with docker' rather than best practice... I guess this means things like this are a bit out of scope?
