### ISSUE TITLE
curl returns file download, not file context

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/docker-introduction#50]
The curl returns a redirect, because it is a file download... do we want that?? it is problematic on the docker run config episode... see [todo](https://github.com/UoMResearchIT/docker-introduction/blob/92204d50f09c09125ba0ec712e7f4b48dfbeac1f/episodes/docker-run-configuration.Rmd#L67).

**Comment by OliverWoolland** [comment]
Can't repro... how up to date are the images on dockerhub?
