### ISSUE TITLE
TMP or TEMP?

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/docker-introduction#68]
Should the setup be [TMPDIR](https://github.com/UoMResearchIT/docker-introduction/blob/261a11cff628c5e0bdb6379f038abb30baa57058/learners/setup.md?plain=1#L62), or [TEMPDIR](https://github.com/UoMResearchIT/docker-introduction/blob/261a11cff628c5e0bdb6379f038abb30baa57058/learners/setup.md?plain=1#L65) (also [here](https://github.com/UoMResearchIT/docker-introduction/blob/261a11cff628c5e0bdb6379f038abb30baa57058/learners/setup.md?plain=1#L65)?

**Comment by OliverWoolland** [comment]
TMPDIR I thinik
