### ISSUE TITLE
Slow down giffs or use mp4 instead?

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/docker-introduction#72]
might be better to use videos, if they work, so that the "start" is obvious...

**Comment by OliverWoolland** [comment]
![image](https://github.com/user-attachments/assets/6738a34d-1d1d-4586-93fb-cc8d8176592b)

**Comment by fherreazcue** [comment]
Maybe use a "slidewshow" approach instead? @OliverWoolland @nigeldgreen you had suggestions for the sort of html that I can try out?

**Comment by OliverWoolland** [comment]
I've sent you a snippet on teams :)

**Comment by nigeldgreen** [comment]
This is the one I have used before: https://owlcarousel2.github.io/OwlCarousel2/. It's pretty good as libraries go, but not sure how/if it would integrate into the page.

**Comment by fherreazcue** [comment]
could not make carousels work... using tabs instead.
